services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Moscow/Europe
    volumes:
      - ./config:/config
      - /mnt/library:/library
      - /mnt/cloud:/cloud
      - /mnt/work:/work
      - /mnt/photos/phone:/phone
      - /mnt/scripts:/scripts
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
    networks:
      - nasnet
networks:
  nasnet:
    external: true
