- name: Create users
  ansible.builtin.user:
    name: "{{ item.name }}"
    password: "{{ item.password | ansible.builtin.password_hash('sha512') }}"
    update_password: on_create
    state: present
    shell: /bin/bash
    create_home: false
  loop: "{{ users_to_create }}"
  no_log: true