version: "3"

services:
  filebrowser:
    image: hurlenko/filebrowser
    user: "1000:1000"
    ports:
      - 8083:8080
    volumes:
      - /mnt/hdd:/data
      - ./config:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: always
